server:
  port: 9005
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.207.111
      port: 27017
      database: tensquare_spit
  redis:
    host: 192.168.207.111
    port: 6379